# Getting Started with NumPy - Lab

## Introduction

Now that we have introduced NumPy, let's put it to practice. In this lab, we are going to be creating arrays, performing operations on them, and returning new array all using the NumPy library. Let's get started!

## Objectives

You will be able to: 

* Understand how to initialize NumPy arrays from nested Python lists, and access elements using square brackets
* Understand the shape attribute on NumPy arrays
* Understand how to create arrays from scratch including np.zeros, np.ones, np.full
* Learn to perform scalar and vector math  

## Import NumPy under the standard alias

In [1]:
#Your code here
import numpy as np

## Generating Some Mock Data

Create a NumPy Array for each of the following:
    1. Using a range
    2. Using a Python List
    
Below, create a list in Python that has 5 elements (i.e. [0,1,2,3,4]) and assign it to the variable `py_list`. 

Next, do the same, but instead of a list, create a range with 5 elements and assign it to the variable, `py_range`.

Finally, use the list and range to create NumPy arrays and assign the array from list to the variable `array_from_list`, and the array from the range to the variable `array_from_range`.

In [32]:
#Your code here
array_from_range = np.array([0,1,2,3,4])
array_len= len(array_from_range)
print(array_from_range)
print(array_len)

[0 1 2 3 4]
5


Next, we have a list of heights and weights and we'd like to use them to create a collection of BMIs. However, they are both in inches and pounds (imperial system), respectively. 

Let's use what we know to create NumPy arrays with the metric equivalent values, (height in meters & weight in kg).

> **Remember:** *NumPy can make these calculations a lot easier and with less code than a list!*

> 1.0 inch = 0.0254 meters

> 2.2046 lbs = 1 kilogram

In [41]:
# use the conversion rate for turning height in inches to meters
list_height_inches = [65, 68, 73, 75, 78]
array_conversion_kg= np.full(array_len,0.0254)
inches_to_meters = np.multiply(np.array(list_height_inches),array_conversion_kg)
print(inches_to_meters)
print(type(inches_to_meters))
print(inches_to_meters.shape)
print(len(inches_to_meters))
print(array_conversion_kg)
#Your code here

[1.651  1.7272 1.8542 1.905  1.9812]
<class 'numpy.ndarray'>
(5,)
5
[0.0254 0.0254 0.0254 0.0254 0.0254]


In [42]:
# use the conversion rate for turning weight in pounds to kilograms
list_weight_pounds = [150, 140, 220, 205, 265]
pounds_to_kilo = np.divide(np.array(list_weight_pounds),2.2)
print(pounds_to_kilo)
pounds_to_kilo.shape

#your code here

[ 68.18181818  63.63636364 100.          93.18181818 120.45454545]


(5,)

The metric formula for calculating BMI is as follows:

> BMI = weight (kg) ÷ height^2 (m^2)

So, to get BMI we divide weight by the squared value of height. For example, if i weighed 130kg and was 1.9 meters tall, the calculation would look like:

> BMI = 130 / (1.9*1.9)

Use the BMI calculation to create a NumPy array of BMIs

In [43]:
#Your code here
BMI = pounds_to_kilo/np.power(inches_to_meters,2)
print(BMI)

len(BMI)


[25.01349812 21.33143618 29.08619066 25.67681903 30.68785649]


5

## Create an identity vector using `np.ones()`

In [44]:
#Your code here
identity = np.ones(len(BMI))
print(identity)

[1. 1. 1. 1. 1.]


## Multiply the BMI_array by your identity vector

In [46]:
#Your code here
BMI_times_vector = np.multiply(BMI, identity)
BMI_times_vector

array([25.01349812, 21.33143618, 29.08619066, 25.67681903, 30.68785649])

In [ ]:
grade['pass'].map(lambda x: x>80)

## Level Up: Using NumPy to Parse a File
The pandas library that we've been using is built on top of NumPy; all columns/series in a Pandas DataFrame are built using NumPy arrays. To get a better idea of a how a built in method like pd.read_csv() works, we'll try and recreate that here!

In [3]:
#Open a text file (csv files are just plaintext separated by commas)
f = open('bp.txt')
n_rows = len(f.readlines())
print('The file has {} lines.'.format(n_rows)) #Print number of lines in the file
f = open('bp.txt') #After using readlines, we must reopen the file
n_cols = (len(f.readline().split('\t'))) #The file has values separated by tabs; we read the first line and check it's length.

f = open('bp.txt')

#Your code here
#Pseudocode outline below
#1) Create a matrix of zeros that is the same size of the file
matrix_file_size = np.zeros([n_rows, n_cols])
#2) Iterate through the file: "for line in f:" Hint: using enumerate will also be required
#BRAIN STORM:
for line in f:
    line_split = line.split('\t')
    for i in r
    

#for i , line in enumerate(f): #enumerate returns tubles (i,line) 
    #if i > 0: #this is to show that we are skipping the first line --> line[0]
        #matrix_file_size[i,:] = line.split('\t') #shows that the row in matrix[i] will be replaced with
        #with whatever the stuff in the line is splited by tab

#print(matrix_file_size)
    


    #3) Update each row of the matrix with the new stream of data
    #Hint: skip the first row (it's just column names, not the data.)
#4) Preview your results; you should now have a NumPy matrix with the data from the file


The file has 21 lines.


In [4]:
f = open('bp.txt')
list_matrix = []
header_line = f.readline()  # junk the column names

for line in f:  # does this implicitly do f.readline()?
#print(line)
    num_line = line.split('\t')
    for j in range(len(num_line)):      # Cast these entries to float
        num_line[j] = float(num_line[j])
        list_matrix.append(num_line) # Tack the array on to a list of lists

#3) Update each row of the matrix with the new stream of data
   #Hint: skip the first row (it's just column names, not the data.)
M = np.array(list_matrix)

#4) Preview your results; you should now have a NumPy matrix with the data from the file
print(M)

[[  1.  105.   47.  ...   5.1  63.   33. ]
 [  1.  105.   47.  ...   5.1  63.   33. ]
 [  1.  105.   47.  ...   5.1  63.   33. ]
 ...
 [ 20.  122.   56.  ...   7.   75.   99. ]
 [ 20.  122.   56.  ...   7.   75.   99. ]
 [ 20.  122.   56.  ...   7.   75.   99. ]]


## Summary

In this lab, we practiced creating NumPy arrays from both lists and ranges. We then practiced performing math operations like converting imperial measurements to metric measurements on each element of a NumPy array to create new arrays with new values. Finally, we used both of our new NumPy arrays to operate on each other and create new arrays containing the BMIs from our arrays containing heights and weights.